name: sync

on:
  schedule:
    - cron: '30 5 * * 1,3'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: CGO_ENABLED=0 go build -o app
